#!/usr/bin/env bash
# Ping 5 times the address given in arg, if no args given display usage

if [[ -z "$1" ]]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$1"
