#!/usr/bin/env bash
# Modifies the hosts file (Caution: This can break things!)

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new
sudo sh -c "echo '8.8.8.8 facebook.com' >> /etc/hosts"
cp -f ~/hosts.new /etc/hosts